// This file is auto-generated by: pnpm --filter @appdeportes/supabase db:types
// Do not edit manually. Run the command above after schema changes.
export type Json =
  | string
  | number
  | boolean
  | null
  | { [key: string]: Json | undefined }
  | Json[];

export type Database = {
  public: {
    Tables: {
      countries: {
        Row: {
          id: string;
          name: string;
          code: string;
          currency_code: string;
          currency_symbol: string;
          is_active: boolean;
          created_at: string;
        };
        Insert: {
          id?: string;
          name: string;
          code: string;
          currency_code: string;
          currency_symbol: string;
          is_active?: boolean;
          created_at?: string;
        };
        Update: Partial<Database['public']['Tables']['countries']['Insert']>;
      };
      cities: {
        Row: {
          id: string;
          country_id: string;
          name: string;
          is_active: boolean;
          created_at: string;
        };
        Insert: {
          id?: string;
          country_id: string;
          name: string;
          is_active?: boolean;
          created_at?: string;
        };
        Update: Partial<Database['public']['Tables']['cities']['Insert']>;
      };
      sports: {
        Row: {
          id: string;
          name: string;
          icon: string | null;
          formats: string[];
          is_active: boolean;
          created_at: string;
        };
        Insert: {
          id?: string;
          name: string;
          icon?: string | null;
          formats?: string[];
          is_active?: boolean;
          created_at?: string;
        };
        Update: Partial<Database['public']['Tables']['sports']['Insert']>;
      };
      city_sports: {
        Row: {
          id: string;
          city_id: string;
          sport_id: string;
          is_active: boolean;
          created_at: string;
        };
        Insert: {
          id?: string;
          city_id: string;
          sport_id: string;
          is_active?: boolean;
          created_at?: string;
        };
        Update: Partial<Database['public']['Tables']['city_sports']['Insert']>;
      };
      plans: {
        Row: {
          id: string;
          name: string;
          price: number;
          max_matches_per_month: number;
          created_at: string;
        };
        Insert: {
          id?: string;
          name: string;
          price: number;
          max_matches_per_month: number;
          created_at?: string;
        };
        Update: Partial<Database['public']['Tables']['plans']['Insert']>;
      };
      users: {
        Row: {
          id: string;
          name: string;
          email: string;
          phone: string | null;
          avatar: string | null;
          role: 'player' | 'owner' | 'admin';
          is_pro: boolean;
          matches_played: number;
          created_at: string;
        };
        Insert: {
          id: string;
          name: string;
          email: string;
          phone?: string | null;
          avatar?: string | null;
          role?: 'player' | 'owner' | 'admin';
          is_pro?: boolean;
          matches_played?: number;
          created_at?: string;
        };
        Update: Partial<Database['public']['Tables']['users']['Insert']>;
      };
      owner_profiles: {
        Row: {
          id: string;
          user_id: string;
          plan_id: string | null;
          subscription_status: 'active' | 'inactive' | 'trial' | 'cancelled';
          cancellation_count: number;
          created_at: string;
        };
        Insert: {
          id?: string;
          user_id: string;
          plan_id?: string | null;
          subscription_status?: 'active' | 'inactive' | 'trial' | 'cancelled';
          cancellation_count?: number;
          created_at?: string;
        };
        Update: Partial<Database['public']['Tables']['owner_profiles']['Insert']>;
      };
      fields: {
        Row: {
          id: string;
          owner_id: string;
          city_id: string;
          name: string;
          address: string;
          latitude: number;
          longitude: number;
          images: string[];
          created_at: string;
        };
        Insert: {
          id?: string;
          owner_id: string;
          city_id: string;
          name: string;
          address: string;
          latitude: number;
          longitude: number;
          images?: string[];
          created_at?: string;
        };
        Update: Partial<Database['public']['Tables']['fields']['Insert']>;
      };
      matches: {
        Row: {
          id: string;
          field_id: string;
          sport_id: string;
          type: 'open' | 'reservation';
          status: 'open' | 'confirmed' | 'completed' | 'cancelled';
          date: string;
          start_time: string;
          end_time: string;
          format: string;
          price_per_player: number | null;
          total_price: number | null;
          min_players: number | null;
          max_players: number | null;
          confirmation_deadline: string | null;
          cancelled_by: string | null;
          cancellation_reason: string | null;
          enrolled_count_at_cancellation: number | null;
          is_visible: boolean;
          created_at: string;
        };
        Insert: {
          id?: string;
          field_id: string;
          sport_id: string;
          type: 'open' | 'reservation';
          status?: 'open' | 'confirmed' | 'completed' | 'cancelled';
          date: string;
          start_time: string;
          end_time: string;
          format: string;
          price_per_player?: number | null;
          total_price?: number | null;
          min_players?: number | null;
          max_players?: number | null;
          confirmation_deadline?: string | null;
          cancelled_by?: string | null;
          cancellation_reason?: string | null;
          enrolled_count_at_cancellation?: number | null;
          is_visible?: boolean;
          created_at?: string;
        };
        Update: Partial<Database['public']['Tables']['matches']['Insert']>;
      };
      enrollments: {
        Row: {
          id: string;
          match_id: string;
          user_id: string;
          status: 'pending' | 'confirmed' | 'cancelled' | 'refunded';
          attended: boolean | null;
          payment_id: string | null;
          created_at: string;
        };
        Insert: {
          id?: string;
          match_id: string;
          user_id: string;
          status?: 'pending' | 'confirmed' | 'cancelled' | 'refunded';
          attended?: boolean | null;
          payment_id?: string | null;
          created_at?: string;
        };
        Update: Partial<Database['public']['Tables']['enrollments']['Insert']>;
      };
      payments: {
        Row: {
          id: string;
          match_id: string;
          enrollment_id: string | null;
          amount: number;
          method: 'in_app' | 'in_person';
          status: 'pending' | 'completed' | 'refunded' | 'failed';
          provider: string | null;
          provider_transaction_id: string | null;
          created_at: string;
        };
        Insert: {
          id?: string;
          match_id: string;
          enrollment_id?: string | null;
          amount: number;
          method: 'in_app' | 'in_person';
          status?: 'pending' | 'completed' | 'refunded' | 'failed';
          provider?: string | null;
          provider_transaction_id?: string | null;
          created_at?: string;
        };
        Update: Partial<Database['public']['Tables']['payments']['Insert']>;
      };
    };
    Views: Record<string, never>;
    Functions: {
      is_admin: {
        Args: Record<string, never>;
        Returns: boolean;
      };
      is_owner_or_admin: {
        Args: Record<string, never>;
        Returns: boolean;
      };
    };
    Enums: {
      user_role: 'player' | 'owner' | 'admin';
      subscription_status: 'active' | 'inactive' | 'trial' | 'cancelled';
      match_type: 'open' | 'reservation';
      match_status: 'open' | 'confirmed' | 'completed' | 'cancelled';
      enrollment_status: 'pending' | 'confirmed' | 'cancelled' | 'refunded';
      payment_method: 'in_app' | 'in_person';
      payment_status: 'pending' | 'completed' | 'refunded' | 'failed';
    };
  };
};
